---
- name: Import Judges from Git in OpenShift
  hosts: localhost
  vars:
    git_repo_url: "https://github.com/catalyst-ctfd/catalyst.git"
    app_name: "judge"
    project_name: "judge"

  tasks:
    - name: Get the cluster console URL
      shell: oc get routes --all-namespaces | grep console-openshift | awk '{ print $3 }'
      register: oc_output

    - name: Extract the cluster domain
      set_fact:
        extracted_domain: "{{ oc_output.stdout.split('apps.')[1] }}"

    - name: create {{ project_name }} namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
        state: present
        wait: yes
      retries: 20
      delay: 15

    - name: Create ConfigMap
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: judge-settings
            namespace: judge
          data:
            cluster-domain: "{{ extracted_domain }}"

    - name: Repo SSH key
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'ssh-secret.yaml') }}"

    - name: Bottle - BuildConfig
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'bottle-buildconfig.yaml') }}"

    - name: Bottle - Imagestream
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'bottle-imagestream.yaml') }}"

    - name: Start the Build
      command: oc start-build bottle -n judge
      register: build_result
      changed_when: "'completed' not in build_result.stdout"

    - name: Bottle - Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'bottle-deployment.yaml') }}"

    - name: Morse - BuildConfig
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'morse-buildconfig.yaml') }}"

    - name: Morse - Imagestream
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'morse-imagestream.yaml') }}"

    - name: Start the Build
      command: oc start-build morse -n judge
      register: build_result
      changed_when: "'completed' not in build_result.stdout"

    - name: Morse - Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'morse-deployment.yaml') }}"

    - name: hello-world - BuildConfig
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'hello-world-buildconfig.yaml') }}"

    - name: hello-world - Imagestream
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'hello-world-imagestream.yaml') }}"

    - name: Start the Build
      command: oc start-build hello-world -n judge
      register: build_result
      changed_when: "'completed' not in build_result.stdout"

    - name: hello-world - Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'hello-world-deployment.yaml') }}"

    - name: aloha - BuildConfig
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'aloha-buildconfig.yaml') }}"

    - name: aloha - Imagestream
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'aloha-imagestream.yaml') }}"

    - name: Start the Build
      command: oc start-build aloha -n judge
      register: build_result
      changed_when: "'completed' not in build_result.stdout"

    - name: aloha - Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'aloha-deployment.yaml') }}"

    - name: postgres - BuildConfig
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'postgres-buildconfig.yaml') }}"

    - name: postgres - Imagestream
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'postgres-imagestream.yaml') }}"

    - name: Start the Build
      command: oc start-build postgres -n judge
      register: build_result
      changed_when: "'completed' not in build_result.stdout"

    - name: postgres - Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'postgres-deployment.yaml') }}"

    - name: monkey-business - ServiceAccount
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'serviceaccount.yaml') }}"

    - name: Get Token for Service Account
      shell: oc get secret $(oc get secret -n judge | grep judge-sa-token | awk '{ print $1 }') -o json -n judge | jq -r .data.token
      register: service_account_token

    - name: Update Kubernetes secret YAML with the extracted data
      replace:
        path: monkey-business-secret.yaml
        regexp: 'judge-sa-token'
        replace: "{{ service_account_token.stdout }}"

    - name: monkey-business - Secret
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'monkey-business-secret.yaml') }}"

    - name: Revert the token back to the original string
      replace:
        path: monkey-business-secret.yaml
        regexp: "{{ service_account_token.stdout }}"
        replace: "judge-sa-token"

    - name: monkey-business - BuildConfig
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'monkey-business-buildconfig.yaml') }}"

    - name: monkey-business - Imagestream
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'monkey-business-imagestream.yaml') }}"

    - name: Start the Build
      command: oc start-build monkey-business -n judge
      register: build_result
      changed_when: "'completed' not in build_result.stdout"
    
    - name: monkey-business - Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'monkey-business-deployment.yaml') }}"