apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_world
  namespace: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_world
  template:
    metadata:
      labels:
        app: hello_world
        deployment: hello_world
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/judge/hello_world:latest
          name: hello_world
          ports:
            - containerPort: 8080
