apiVersion: v1
kind: List
items:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ""
        app.openshift.io/vcs-uri: git@github.com:catalyst-ctfd/catalyst.git
      labels:
        app: bottle
        app.kubernetes.io/component: bottle
        app.kubernetes.io/instance: bottle
        app.kubernetes.io/name: bottle
        app.kubernetes.io/part-of: judge
        app.openshift.io/runtime: python
        app.openshift.io/runtime-version: 3.9-ubi8
      name: bottle
      namespace: judge
    spec:
      failedBuildsHistoryLimit: 5
      output:
        to:
          kind: ImageStreamTag
          name: bottle:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: /judge/bottle
        git:
          uri: git@github.com:catalyst-ctfd/catalyst.git
        sourceSecret:
          name: repo-key
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:3.9-ubi8
            namespace: openshift
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - generic:
            secretReference:
              name: bottle-generic-webhook-secret
          type: Generic
        - github:
            secretReference:
              name: bottle-github-webhook-secret
          type: GitHub
        - imageChange: {}
          type: ImageChange
        - type: ConfigChange
    status:
      imageChangeTriggers:
        - from:
            name: python:3.9-ubi8
            namespace: openshift
          lastTriggerTime: null
          lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:e512f90285b41202f219a48f727d11ddc918225568db7904c819052296f68e59
      lastVersion: 1

