apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/route-disabled: "false"
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: git@github.com:catalyst-ctfd/catalyst.git
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"bottle:latest","namespace":"judge"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bottle\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2023-08-31T16:04:35Z"
    generation: 2
    labels:
      app: bottle
      app.kubernetes.io/component: bottle
      app.kubernetes.io/instance: bottle
      app.kubernetes.io/name: bottle
      app.kubernetes.io/part-of: judge
      app.openshift.io/runtime: python
      app.openshift.io/runtime-version: 3.9-ubi8
    name: bottle
    namespace: judge
    resourceVersion: "87226"
    uid: 13679922-54b1-41b1-b8d1-679904fd476d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: bottle
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: bottle
          deployment: bottle
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/judge/bottle@sha256:4b9cf15edf77d16975e6e53a0e15c2edc65ae18bb8af4c2d7d113c09aa909cec
          imagePullPolicy: Always
          name: bottle
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-08-31T16:05:22Z"
      lastUpdateTime: "2023-08-31T16:05:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-08-31T16:04:35Z"
      lastUpdateTime: "2023-08-31T16:05:22Z"
      message: ReplicaSet "bottle-86d5d8b5b4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
