#RHEL UBI + Python in base image

FROM registry.access.redhat.com/ubi8/python-311:1-13

LABEL maintainer="mberube@redhat.com"

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]

EXPOSE 5000