# Use the official MySQL 8.0 image
FROM mysql:8.0

LABEL maintainer="mberube@redhat.com"

# Expose MySQL port
EXPOSE 3306

# Set environment variables for MySQL (ephemeral data)
# ENV MYSQL_ROOT_PASSWORD=rootpassword
# ENV MYSQL_DATABASE=mydatabase
# ENV MYSQL_USER=myuser
# ENV MYSQL_PASSWORD=mypassword

# Optionally copy a SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/

# By default, the MySQL image will handle starting MySQL
# CMD ["mysqld"] is already provided by the image